resource:
   cassandra:
      resource_configuration: file:/usr/local/tomcat/etc/cassandra.conf
management:
   endpoints:
      web:
         exposure:
            include:
             - info
             - health
   endpoint:
      info:
         enabled: true
      health:
         enabled: true
   info:
      env: 
         enabled: true
customer:
   contexts:
      path: /usr/local/tomcat/etc/contexts
store:
   zookeeper:
      host: 172.17.0.1:10024
application:
   zookeeper:
      host: 172.17.0.1:10024
api:
   authorization:
      path: http://172.17.0.1:8090/ExempleAuthorization
      client:
         clientId: resource
         clientSecret: secret
   swagger:
      authorization:
         path: http://localhost:8086/ExempleAuthorization