language: java
jdk:
   - openjdk8
before_script:
  - echo "MAVEN_OPTS='-Xmx1g'" > ~/.mavenrc
script: mvn -s .travis.settings.xml verify -Pservice,it
after_success:
    - bash <(curl -s https://codecov.io/bash)
install: true
sudo: false
cache:
    directories:
        - $HOME/.m2
        - $HOME/.embedded-cassandra